### ISSUE TITLE
Login failed for user 'sa'. Reason: An error occurred while evaluating the password.

### ISSUE THREAD

**Issue by dmonllao** [moodlehq/moodle-db-mssql#9]
Hello good sirs,

I cloned this project to use a mssql copy with fulltext search support (https://github.com/dmonllao/moodle-db-mssql/commit/87e842e3b10c9a4f69f50032e7d7bef0f7dc6f65) I've also modified my moodle-docker clone adding a new mssql.fts MOODLE_DOCKER_DB mode to read from my modle-db-mssql clone and I've used moodle-docker-compose to start it up. After some issues everything went ok but the database creation didn't. I initially thought that I must have done something wrong in my Dockerfile (first time I edit one) But looking at the container logs I found the following:

> [moodle-db-mssql] SQL Server UP
> [moodle-db-mssql] Setting up Moodle data
> 2017-12-04 12:32:40.18 Logon       Error: 18456, Severity: 14, State: 7.
> 2017-12-04 12:32:40.18 Logon       Login failed for user 'sa'. Reason: An error occurred while evaluating the password. [CLIENT: 172.18.0.4]

Looking for info about the error I found https://github.com/Microsoft/mssql-docker/issues/55#issuecomment-288942986 which suggests that may be better to avoid some characters in the password. We are currently using '@' as part of the password. My moodle-db-mssql clone uses microsoft/mssql-server-linux (latest) and this repo uses microsoft/mssql-server-linux:rc1; this is the most noticeable difference I've seen and it may be the reason why nobody else may have faced this problem before. I will investigate this further during this week and do some testing, but we may be interested in changing that '@' for another character if we want to use the latest microsoft/mssql-server-linux version at some point.

BTW, I can't see rc1 listed in https://hub.docker.com/r/microsoft/mssql-server-linux/tags/, there must be something I am missing about how this versioning system works...

**Comment by scara** [comment]
> we may be interested in changing that '@' for another character

https://docs.microsoft.com/en-us/sql/relational-databases/security/strong-passwords looks pretty clear though I'm using this image w/ Moodle since its early stages.
Probably something changed when M$ GAed MSSQL 2017: will look in my dev env too.

👍 for a password change.

> there must be something I am missing about how this versioning system works...

Nothing but M$ removed all the intermediate stages (worth noting that each image had an hard-coded 180 days expiration time).

TIA,
Matteo

P.S.: IIWY I'd add a new issue about improving the current image to include FTS too when https://tracker.moodle.org/browse/MDL-53226 will land into the main stream 😀 .

**Comment by stronk7** [comment]
Hi,

I'm closing this now because it doesn't seem to be a problem. I'm using the "default" password here (having that "@") and everything is working ok. With current versions.

About FTS... you're welcome, of course!
